### ISSUE TITLE
Forecast targets

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid19-forecast-hub-europe#1]
Outline of key decisions agreed or still TBC on the European hub forecast targets.

Variables
- Agreed: Cases & deaths
- [ ] **TBC:** Health system burden - hospital occupancy/admissions?

Time & space
- Agreed: Country-level
- [x] **TBC:** How many weeks? 4-6?

Type
- Agreed: Incident forecasts only, no cumulative
- [x] **TBC:** How many quantiles (24 to match others, or simpler)

Truth data
- Agreed: ECDC `weekly_count` (incidence) per country for cases & deaths
- [ ] **TBC:** Country level health system data

**Comment by sbfnk** [comment]
Variables: re health system to check with ECDC
Time: 4 weeks
Type: possibly: 24 quantiles but allow 5: 0%, 50% and 90% intervals - to be discussed.
Truth data: will need to check with ECDC as there's also a daily non-official scrape of other sources they can provide

**Comment by sbfnk** [comment]
Re type: let's be consistent with everywhere else: 24 quantiles or point forecasts

**Comment by sbfnk** [comment]
And variables will be cases and deaths initially.
