### ISSUE TITLE
Update static visualisations

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#10]
See https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/code/visualization/plot_current_forecasts.R - this is probably best replaced by something that uses `scoringutils`

This is to create a static visualisation for the github page - not sure we need that, probably best to focus on generating a general summary Rmd.

**Comment by nikosbosse** [comment]
where would that static visualisation appear?

**Comment by sbfnk** [comment]
I don‘t think we need that - better would be to have something along the lines of this I think:
https://github.com/reichlab/covid19-forecast-hub/tree/master/code/reports

**Comment by sbfnk** [comment]
Now exists as of #110 and #124.
