### ISSUE TITLE
Update validation scripts

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#11]
living [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/tree/main/code/validation) - also taking note of https://github.com/reichlab/covid19-forecast-hub/issues/2594

**Comment by sbfnk** [comment]
For the Germany/Poland hub especially https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/code/validation/validate_filenames.py and https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/code/validation/test-formatting.py

**Comment by sbfnk** [comment]
See here for the US version: https://github.com/reichlab/covid19-forecast-hub/wiki/Data-Validation (Germany/Poland version diverged in June)

**Comment by sbfnk** [comment]
Should include a check of the filename to match the submission day.

**Comment by kathsherratt** [comment]
Copying over here from slack channel discussion

> Only the following needs to be changed in the validation scripts 
> - The FIPS_CODES dict in covid19-forecast-hub-de/code/validation/covid19.py 
> - the list COUNTRIES in covid19-forecast-hub-de/code/validation/test-formatting.py

We will need to decide which standard of country codes for some of this - currently [TBC](https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/docs/decisions.md)

**Comment by kathsherratt** [comment]
@sbfnk , re. comment above to include a filename check to match submission day. The current validation includes that the filename matches the `forecast_date` column (function `filename_match_forecast_date()` in `test-formatting.py`). 

Is this what you meant, or did you intend a check that the filename matches the date the PR is made (or is within the Thu-Mon range of accepted dates each week)?

**Comment by sbfnk** [comment]
in the US they are working on "a check for submissions that come in with a date in the filename (i.e. the forecast_date ) not equal to today or today+1 . This will throw a warning and in general [they] will ask teams to resubmit their files with an updated forecast_date and possibly updated targets in their file." - this seems like a good idea. I think @nikosbosse has some views on this, too.

**Comment by nikosbosse** [comment]
I have a _very strong_ preference to force any submissions to have the date be _exactly_ the last day of the submission period. This makes it very easy and unambiguous to find out for which week something was submitted and we can use the filename as submission date without having to do any fiddling.

**Comment by seabbs** [comment]
I agree.
