### ISSUE TITLE
Target-specific launch dates

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#1176]
It would be good to make the launch dates in [forecasthub.yml](https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/d1d5a1ba40923c0935d9e5a6f590dfdde8f266b3/forecasthub.yml#L11) target-specific. In particular, since we completely overhauled the hospitalisation data we should use this to exclude previous forecasts as they'll be mismatched to the current data.

**Comment by Bisaloo** [comment]
In the end, we decided to add the previous dates to `anomalies.csv` and Kath did it in https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/1219.
