### ISSUE TITLE
Update technical wiki

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid19-forecast-hub-europe#12]
https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki

Using 

https://github.com/KITmetricslab/covid19-forecast-hub-de/wiki

**Comment by sbfnk** [comment]
Taking inspiration also from https://github.com/reichlab/covid19-forecast-hub/wiki

**Comment by kathsherratt** [comment]
To get something in place I have arbitrarily written the wiki using some assumptions about the [decisions still to be taken](https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/docs/decisions.md). Noting these here to be edited as the decisions are taken.

- Truth data = ECDC ([here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#truth-data), [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Forecast-format#target))
- Location = ISO-3 code ([here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Forecast-format#location))
- Location = national only, no subnational ([here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#location))
- Horizon = 1 to 4 weekly ([here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#horizon), [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Forecast-format#target))
- Submission dates = Friday to Monday ([as example](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#horizon))
- Frequency = weekly ([here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#frequency))

**Comment by kathsherratt** [comment]
Listing progress on wiki - feel free to add pages or leave notes/suggestions here

- - [x] Preparing to submit
  - [x] Creating a sub-directory
  - [x] Meta data
  - [x] Licensing
- Forecasting
  - [x] Targets and horizons
  - [x] Forecast format
  - [ ] Checking your submission
- Submitting
  - [ ] Submission via GitHub
  - [ ] Automatic Validation Checks
  - [ ] Troubleshooting

**Comment by kathsherratt** [comment]
All the key content is now there. The images  in the [submission guide](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Submission-via-website) showing how to PR need to be updated to the Europe hub, but all text is correct.

**Comment by kathsherratt** [comment]
Completed, including updates to
- Use JHU data
- Use Epiweeks
- Include scenario_id column
- Screenshots in submission guide updated
