### ISSUE TITLE
Ensembles/data missing in visualisation

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#1237]
Some data/forecasts (only from the ensemble I think) are missing in the visualisation, e.g.

[Spain hospitalisation data](https://covid19forecasthub.eu/visualisation.html?models=EuroCOVIDhub-ensemble&location=ES&target=hosp)

[Spain case ensemble forecasts](https://covid19forecasthub.eu/visualisation.html?models=EuroCOVIDhub-ensemble&location=ES)

**Comment by Bisaloo** [comment]
For the missing forecasts, it's fixed by https://github.com/epiforecasts/covid19-forecast-hub-europe/commit/33e6133a768ceb69222c4f52f731cd20c177b0e2.

**Comment by sbfnk** [comment]
Shouldn't this morning's run include the case ensemble built yesterday?

**Comment by Bisaloo** [comment]
Yes, you just don't see it at the moment because of the lazy cache but I verified locally and everything looks fine.

**Comment by Bisaloo** [comment]
For the truth data, Spain is absent from https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/2d4b0d8b4571a4deda9ef6a7bd09fc98527c6988/data-truth/ECDC/truth_ECDC-Incident%20Hospitalizations.csv

**Comment by sbfnk** [comment]
OK this makes sense as it was previously available but no longer now - so once we include the anomalies file in the visualisations these will be gone. Thanks!
