### ISSUE TITLE
Duplicate validation files

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#159]
Am I right in thinking, @JADEUSC, that everything in `code/validation` is no longer needed here except the daily truth data check? If not we'll remove the files here so as to avoid confusion.

**Comment by sbfnk** [comment]
We'll keep both in but they're now synchronised daily as of #158 - everything in `viz` is just for visualisation so there is some unavoidable duplication.

**Comment by JADEUSC** [comment]
[This](https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/code/validation/commit_dates.csv) file keeps track of all the commit dates and is updated with the Vis/Val/Eval job every day. Everything else (except the truth checks) should be obsolete.
