### ISSUE TITLE
Enable local checks

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#187]
At the moment the local checks don't work (and the corresponding section in the wiki is out of date).

**Comment by kathsherratt** [comment]
Local checks can now be run, via the validations submodule: https://github.com/JADEUSC/covid19-forecast-hub-europe-validations/pull/7

Instructions in the [wiki](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Check-submission). Essentially local checks require one manual intervention at the start - to add the new files to be checked to the `validations/forecasts` folder. Then checks run as normal (as in the normal gh action triggered by PR), on running `main.py` with the `validation` submodule as the working directory.

Think this should close the issue. There is one add-in piece checking PRs by reference number ([here](https://github.com/JADEUSC/covid19-forecast-hub-europe-validations/pull/7#issuecomment-825473614)) which @JADEUSC may look at.

**Comment by kathsherratt** [comment]
Closing - as above, local checks can be run and the wiki is up to date so this issue is solved. Please re-open if any problems of course.

**Comment by JADEUSC** [comment]
The changes are only present in JADEUSC/covid19-forecast-hub-europe-validations, but the submodule is EPIFORECASTS/covid19-forecast-hub-europe-validations. To update this repo the following PR should be merged:
https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/pull/11

**Comment by kathsherratt** [comment]
Ah my bad, thanks for the reminder!
