### ISSUE TITLE
Switch all location codes to three-letter ISO?

### ISSUE THREAD

**Issue by jbracher** [epiforecasts/covid19-forecast-hub-europe#20]
The ECDC data use the ISO 3166-1 alpha-3 format for county codes (https://www.ecdc.europa.eu/sites/default/files/documents/2021-01-13_Variable_Dictionary_and_Disclaimer_national_weekly_data.pdf). After speaking to Seb I'm therefore using these in all materials I prepare for the RKI app programmers. I think it would be helpful to settle on one format quite soon and switch all checks and files to that (this one contains some other two-letter format: https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/data-processed/LANL-GrowthRate/2021-01-13-LANL-GrowthRate.csv).

If we land on something other than the three-letter ISO it would be great to know soon in order to avoid too much back and forth with Fabian from RKI.

**Comment by jbracher** [comment]
Moved to two-letter ISO

**Comment by kathsherratt** [comment]
Hi Johannes, sorry I hadn't commented on this earlier. Thank you so much for preparing all the materials for the data viz - it's a massive help.

I had actually assumed the default would be ISO-3 - as it comes with the JHU data and was suggested in the [decision doc](https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/docs/decisions.md). I've been using ISO-3 in the [validation updates](https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/17/files#diff-6c3ec431e543e74b26cd10cfe8e93f3d86b641284bdf850644d432f5bc515aa0), but realise without merging this is a bit unclear. However no problem to switch over to ISO-2.

@sbfnk please could you confirm ISO-2 or ISO-3?

**Comment by sbfnk** [comment]
I think we've had conflicting messages (latest of which having been ISO-2). Will confirm on Monday.

**Comment by sbfnk** [comment]
ISO-2 confirmed.
