### ISSUE TITLE
Copy file github action

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid19-forecast-hub-europe#205]
I see: 

https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/0ed6936bd0bb67f3bb6e76bfd16144a78ef9fbf3/.github/workflows/reports_eval.yml#L27

but the action has been forked to the epiforecast repo (presumably for safety) and so maybe that version should be used instead?

**Comment by sbfnk** [comment]
Work in progress: https://github.com/epiforecasts/covid19-forecast-hub-europe/commit/eb7239dfc4a840860524152ec20d20901c0f7157
