### ISSUE TITLE
Switch to JHU truth data

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid19-forecast-hub-europe#21]
Impacts:
- `code/validation`
- `data-truth`
- `.github/workflows`
- travis / github actions

**Comment by dwolffram** [comment]
I've just added a script for downloading and processing JHU data ([jhu_download.py](https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/code/auto_download/jhu_download.py)). Still needs to be added to github actions for daily updates.

**Comment by seabbs** [comment]
I've added and tested the Github action for this so closing. Scheduled at 12 along with the ECDC extract.

**Comment by kathsherratt** [comment]
Thanks so much both! 

Just for completeness, noting here that I've also updated `check-truth.py` (though this lives on the update-validation branch yet to be merged)
