### ISSUE TITLE
Comments Wiki

### ISSUE THREAD

**Issue by jbracher** [epiforecasts/covid19-forecast-hub-europe#26]
I read through the wiki which already looks really nice. I fixed some small stuff and listed further comments below (stuff I didn't feel comfortable editing directly).

* When creating a fork, teams should deactivate actions. This can be done via (in their own fork) Settings -> Actions ->  Disable Actions. Otherwise they will permanently receive notifications about (usually failed) runs of actions.
* The link to a template metadata file [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Creating-a-team-directory#metadata) does not work.
* Link to example metadata file [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Meta-data) does not work.
* Example metadata file probably still needs to be added? I only found https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/template/metadata-ABC-exampleModel1.txt which seems outdated.
* The field `team_model` mentioned [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Meta-data#team_model) does not (or no longer) seem to exist in the US nor DE/PL Hub. Should this be `model_abbr`?
* Is `institional_affil` [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Meta-data#institional_affil) a typo? It's the same in the US repo, so maybe I'm missing something.
* Should be JHU data rather than ECDC [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Meta-data#data_inputs)?
* I suggest to write "Weekly new Covid-19 cases" and "Weekly new Covid-19 cases" [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#targets-1).
* More generally I noticed some incoherence with respect to capitalization of the word "COVID"/"Covid". [On the landing page](https://github.com/epiforecasts/covid19-forecast-hub-europe#european-covid-19-forecast-hub) "COVID" is used in the title and "Covid" in most other places.
* [Here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#truth-data) ISO3 codes are mentioned. May be confusing given that we switched to ISO2. Maybe add to the list of differences?
* I wonder if any mention of data revisions could be added in the section on JHU data.
* Is it correct that forecasts beyond four weeks are not accepted? This seems to be implied [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#horizon)
* The link to the date conversion template [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#date-format) does not work.
* Is it correct that the `forecast_date` needs to be the Monday even if the forecast is issued on a Thursday? I think this differs from US practice and should be stated more clearly. I this is the case I will add it to the wiki page on transitioning.
* Still says ISO3 [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Targets-and-horizons#location)
* `scenario_id` is currently not marked as optional. Should it be?
* `location_name` is not mentioned. I think that is a good idea, but just wanted to make sure.
* The phrase "This is the date for the forecast `target` and will be the Sunday at the end of the week time period. We provide a [template csv](../template/ecdc_week_to_date.csv) to convert between an ECDC week and its end date." [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Forecast-format) seems outdated. There are some more mentions of ECDC which should probably be changed to JHU. Also, there is a mention of ISO3 which should probably be updated.
* In "This value indicates whether that row corresponds to a point forecast or a quantile forecast. Point forecasts are used in visualization, while quantile forecasts are used in visualization and in ensemble construction." [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Forecast-format) I would add that both are used in evaluation.
* Concerning quantiles  [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Forecast-format): The US Hub does not enforce that all quantiles are submitted. Do we? Some US models submit just 3 or 7 quantiles.
* The functionality of adding a folder name to the Python call (mentionen [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Check-submission)) is something Jannik added. You should make sure it is also present in your implementation. Also, I wonder how that will interact with the update of the validation scripts.
* [Here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Submission-via-website#Subsequent-Submissions) it says that "the forecast_date is either the date the pull request was submitted or the previous date" which is in conflict with the instruction to always use a Monday.
* The info given [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Troubleshooting-pull-requests) is outdated as it still shows the version using Travis CI rather than Github Actions. We will also need to revise that in the DE+PL Hub (Jannik will do this on Monday).

**Comment by sbfnk** [comment]
Thanks - very useful indeed! I've addressed all of these as suggested except:

> When creating a fork, teams should deactivate actions. This can be done via (in their own fork) Settings -> Actions -> Disable Actions. Otherwise they will permanently receive notifications about (usually failed) runs of actions.

I think this can be solved with a job conditional: https://github.com/epiforecasts/covid19-forecast-hub-europe/commit/05f6b11cc1c960a096d27398ae5834d1ab55a817

> Is it correct that the forecast_date needs to be the Monday even if the forecast is issued on a Thursday? I think this differs from US practice and should be stated more clearly. I this is the case I will add it to the wiki page on transitioning.

I think our latest thinking was that the date in the file name should be the submission date but the date in the file can be different.

> Is it correct that forecasts beyond four weeks are not accepted? This seems to be implied here.

I don't think >4 weeks should fail the validation but I don't expect us to ever use/evaluate/ensemble for anything longer. I've rephrased this. 

> Concerning quantiles here: The US Hub does not enforce that all quantiles are submitted. Do we? Some US models submit just 3 or 7 quantiles. 

What do you do in DE/PL? The wiki seems to suggest all 23 quantiles need to be specified but I guess one could accept fewer if that's more inclusive (though doesn't that then always restrict one to the minimal set in any evaluation/ensemble?).

> The functionality of adding a folder name to the Python call (mentionen here) is something Jannik added. You should make sure it is also present in your implementation. Also, I wonder how that will interact with the update of the validation scripts." 

Thanks, we'll check.

> Here it says that "the forecast_date is either the date the pull request was submitted or the previous date" which is in conflict with the instruction to always use a Monday.

To be confirmed.

> The info given here is outdated as it still shows the version using Travis CI rather than Github Actions. We will also need to revise that in the DE+PL Hub (Jannik will do this on Monday).

Thanks, we'll check.

**Comment by sbfnk** [comment]
Correction: 

> > Is it correct that the forecast_date needs to be the Monday even if the forecast is issued on a Thursday? I think this differs from US practice and should be stated more clearly. I this is the case I will add it to the wiki page on transitioning.

> I think our latest thinking was that the date in the file name should be the submission date but the date in the file can be different.

I now remember a discussion about this and a decision to aim for maximum compatibility. We won't enforce this, and I've made an update to the PR.

**Comment by jbracher** [comment]
> I think our latest thinking was that the date in the file name should be the submission date but the date in the file can be different.
This is different from US and DE/PL practice but I think it makes sense.

> What do you do in DE/PL? The wiki seems to suggest all 23 quantiles need to be specified but I guess one could accept fewer
We don't enforce this.
