### ISSUE TITLE
Link to forecasthub landing page in the reports should go out of the iframe

### ISSUE THREAD

**Issue by Bisaloo** [epiforecasts/covid19-forecast-hub-europe#265]
Noticed this issue thanks to #264.

When you are browing a report (https://covid19forecasthub.eu/reports.html), and you click on the link to https://covid19forecasthub.eu/, this link opens in the iframe.

If you repeat this a couple of times, you end up with a trippy result of iframes nested in iframes nested in iframes, ...:

![image](https://user-images.githubusercontent.com/10783929/115251928-4c422100-a12b-11eb-989b-354c88d71d4d.png)

The fix would be to force the link to https://covid19forecasthub.eu/ to go out of the iframe.

[This stackoverflow question](https://stackoverflow.com/q/16230959) suggests that it can be achieved by adding `target="_top"` to the `a` element.

**Comment by Bisaloo** [comment]
Instructions for the (R)markdown version: https://community.rstudio.com/t/how-to-direct-a-link-to-another-tab-in-md-files/48737

**Comment by sbfnk** [comment]
Fixed in #277
