### ISSUE TITLE
Ensemble code

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#28]
Review [existing code](https://github.com/epiforecasts/covid19-forecast-hub-europe/tree/main/code/ensemble) and adapt to European hub.

**Comment by jbracher** [comment]
To be honest I think it may make sense to just re-write this altogether. Much of the existing codes deals with handling the various truth data sources and everything will be much easier here. Also, this pulls in evaluation results which I assume will be handled differently in your repo.

**Comment by sbfnk** [comment]
Addressed as of #93
