### ISSUE TITLE
Duplicate metadata files

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid19-forecast-hub-europe#310]
There are currently duplicate metadata files for the `bisop-seirfilterlite` model. 

This can be fixed by deleting the extra `metadata-bisop-seirfilterlite.txt` file which is in the [`bisop-seirfilter`](https://github.com/epiforecasts/covid19-forecast-hub-europe/tree/main/data-processed/bisop-seirfilter) folder.

@cyberklezmer and team, please could you check this?

Thanks,
Kath

**Comment by sbfnk** [comment]
Closed via #470
