### ISSUE TITLE
Data anomalies

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid19-forecast-hub-europe#410]
## 2021-05-24

Forecasts for this week are likely to be affected by anomalies in the data sources for **Ireland** and **France**.

**Republic of Ireland – Death and case counts**
Since 14 May to date, Irish government data (Health Protection Surveillance Centre and Health Service Executive) have not been updated. This was due to a cyberattack on the state health system. This affects all data sources, including the JHU data that we use to evaluate forecasts. The problem is currently unresolved. More information (in English) at:
https://covid19ireland-geohive.hub.arcgis.com/
https://www.bbc.com/news/world-europe-57134916

**France – Case counts**
On 20 May, French government data (Sante Publique France) published a negative count of -348,846 cases. This removed previous double-counting of test data (multiple tests per case). The negative count was included in ECDC public data, but not in JHU or WHO data, which have both reported zero counts from May 20 to date. At the moment we are unclear how these differences will be reconciled. More information (in French and English) at:
https://www.santepubliquefrance.fr/dossiers/coronavirus-covid-19/coronavirus-chiffres-cles-et-evolution-de-la-covid-19-en-france-et-dans-le-monde
- _Update 2021-05-25:_ JHU will now include the negative case count and update the past days' stale data. See: https://github.com/CSSEGISandData/COVID-19/issues/4125

For daily updates on possible data issues affecting Europe, see the [data-truth README](../tree/main/data-truth#readme).

**Comment by kathsherratt** [comment]
## 2021-05-31
No new anomalies this week. 

**Republic of Ireland - Death and case counts** 
The health systems problem continues, with no new data since 2021-05-14.

**Comment by kathsherratt** [comment]
## 2021-06-07

Data this week have changed in Ireland, with no anomalies noted elsewhere.

**Republic of Ireland**
- Death counts
  - Data for deaths continues without updates since 2021-05-14. 
  - The data provider notes that:
  > backdated, validated data on COVID-19 deaths will be published when possible.
- Case counts
  - Data for **cases are now being updated**, as of 2021-06-02. 
  - Data for the 18 days of 2021-05-15 to 2021-06-01 remains missing.
  - Data for 2021-06-02 shows an anomalous spike of 7,917 reported cases. This may be back-distributed in future updates (see below).
  - The data provider notes: 
  > To ensure the continued surveillance and reporting of COVID-19 cases, an alternative approach has been introduced by HPSC, based on a data extract from the HSE Covid Care Tracker (the IT system that records the data collected at telephone interviews with COVID-19 cases and their close contacts). As current data on COVID-19 cases is sourced from this alternative data source, it should be considered provisional and subject to change. When all COVID-19 surveillance systems are restored, cases for this period will be collated and validated on CIDR.

More information from Government of Ireland (in English): https://covid-19.geohive.ie/pages/helpfaqs

**Comment by kathsherratt** [comment]
## 2021-06-14

**Spain**
- Case counts
  - On 10 June 2021, Spain reported an anomalously high case count of 14,004. This is because the Catalonia region reported an additional 9,381 historical cases. These cases were diagnosed between 1 January 2021 and 6 June 2021, but the count has not been back-distributed meaning the 9,381 cases are attributed to 10 June.
  - More information (in Spanish): [RTVE](https://rtve.es/noticias/20210611/mapa-del-coronavirus-espana/2004681.shtml)

**Republic of Ireland**
- Cases counts
  - Cases that were missing between 15 May to 1 June 2021 have now been back-distributed in [JHU](https://github.com/CSSEGISandData/COVID-19/pull/4201), ECDC, and WHO data sources. This has removed the anomalous spike of cases on 2 June (see above).
- Death counts
  - Death counts from 15 May 2021 are still unavailable.

More information from (in English): [Government of Ireland](https://covid-19.geohive.ie/pages/helpfaqs)

**Comment by kathsherratt** [comment]
## 2021-06-28

**Sweden**
- Case and death counts
  - There was a security breach of Swedish data systems over 13 June to 16 June. Data are now available but daily data should be treated with caution. We believe weekly data aggregation should be relatively unaffected.

More information: [FOHM Covid-19](https://experience.arcgis.com/experience/09f821667ce64bf7be6f9f87457ed9aa/page/page_0/)
> Between 13 and 16 June, the SmiNet database was shut down due to security reasons. SmiNet has now been running since June 17, but there is a certain lag in reporting and the statistics per day need to be interpreted over a longer period of time.

**Comment by sbfnk** [comment]
Closing as we currently have no data anomalies - suggest to reopen if/when they reoccur.
