### ISSUE TITLE
Sugestions for eval report

### ISSUE THREAD

**Issue by jbracher** [epiforecasts/covid19-forecast-hub-europe#468]
From the current evaluation report it does not really become clear that mean WIS and mean AE are usually not comparable across teams as the cover different places, weeks etc. Can we add that to the documentation and highlight that the relative skill is the only one which makes an attempt at taking this into account?

Also, maybe we should link to Cramer et al for the explanaiton of the pairwise comparison thing?

**Comment by sbfnk** [comment]
Closed via #473
