### ISSUE TITLE
New team

### ISSUE THREAD

**Issue by RobertWalraven** [epiforecasts/covid19-forecast-hub-europe#49]
Team Name: Robert Walraven
Model: RobertWalraven-ESG

This is the same model that I have been using on the Reichlab hub.  I have been running the same model on ALL of the countries reported by JHU in addition to the US State data.

The model multiple skewed gaussians to fit the case and death data and does not have any epidemiological parameters.  Hence, its full name: Emperical Skewed Gaussians.

**Comment by RobertWalraven** [comment]
I've been making in-house forecasts for some time on all the global countries for which JHU provides data.  I do the global forecasts at the same time and exactly as the US ones in the single run.  Per the discussion today, I'd like to get a list of all the countries you are currently planning to do forecasts for so I know which other ones to omit from the forecast upload.  Also I'd like to be able to test the upload process to be sure I have it right in advance of your first ensemble forecast date.

Please let me know when the hub will be ready for uploading forecasts.

**Comment by sbfnk** [comment]
Hi, thanks for your interest! Great to hear you're planning to submit. You can find a list of countries with corresponding location codes [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/data-locations/locations_eu.csv). We're also planning to add a "how to transition from the US hub" page to the [Wiki](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki), similar to what's [already there](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Transitioning-from-the-German-Polish-COVID19-Forecast-Hub) for teams that are submitting to the German/Polish hub.

**Comment by RobertWalraven** [comment]
I notice that you don't have a Data-Processed folder yet.  I'd like to try uploading some files to my fork, which does have a Data-Processed folder with the Germany-Polish model data, but it doesn't have a folder for me.  Can you tell me how to create that?

I also noticed that the Germany-Polish data has an additional field scenario_id.  Will that be required for data uploads?

**Comment by sbfnk** [comment]
The `data-processed` folder is here:
https://github.com/epiforecasts/covid19-forecast-hub-europe/tree/main/data-processed

You can just create the folder in a fork and then create PR for it to be added with your metadata in it. There are more details on this, and also on the role of the `scenario_id` field, in the Wiki: 
https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki

Could I ask you to have a look at the Wiki and see if your questions are answered there? If anything is missing from the Wiki or unclear we'd like to clarify it there so that others don't run in to the same issues in the future.

**Comment by RobertWalraven** [comment]
I read through all of the Wiki and it appears to be just like what the Reichlab does.   I was able to set up the folder RobertWalraven-ESG in the data-processed folder in my fork and I uploaded the metadata file and a csv file with data for all the countries.   (I was wondering why you restricted the list of countries to 32 instead of the 51 that are usually considered part of Europe.)

The link you gave me for the data-processed folder goes there when I click on the link above, but the subfolder /tree/main, but the subfolder does not show up on the main page, so you have to know that is where it is located.  The Reichlab github site puts the data-processed folder on the main page so it is easily found.

When I ran a PR on the csv data I uploaded, I got an error that doesn't seem to have anything to do with my data - it appears that some setup file is missing.  Is the process for validating data actually working?

**Comment by jbracher** [comment]
Hi Robert, I just set up a Wiki entry on transitioning form the US Hub: https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Transitioning-from-the-US-COVID19-Forecast-Hub Please let us know in case you spot any further differences.

Concerning the checks we were making some changes at the end of last week, but everything should be running smoothly again soon.

**Comment by sbfnk** [comment]
The process *should* be working but I can see that you've got a strange error - we'll investigate. Thanks, Robert, for testing the set up!

**Comment by jbracher** [comment]
We fixed a little mistake in the processing scripts. Could you close and re-open this PR so the validation checks are re-started? Thanks a lot!

**Comment by RobertWalraven** [comment]
I've been trying all morning to get the validation to work, but it seems to be hung up on something to do with file names.  I can't figure out what the error message during validation is telling me is wrong.

**Comment by jbracher** [comment]
I think the problem is that there is a stray metadata file directly in the `data-processed folder.

**Comment by jbracher** [comment]
@RobertWalraven  This one: https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/25404edc039c65f7e9361d7d68a8372faec91135/data-processed/metadata-RobertWalraven-ESG.txt

**Comment by RobertWalraven** [comment]
Thanks for the help.  It looks like you have the data now, which should include all 32 countries.   Let me know when you have had a chance to look at it.

When do you think you will have a visualization link that will display the forecasts?

**Comment by jbracher** [comment]
The visualization including your submitted forecasts can be found here: https://covid19forecasthub.eu/visualisation/

**Comment by sbfnk** [comment]
Thanks again for testing the set up. The forecasts will be used and distributed by the [European Centre for Disease Control and Prevention](https://www.ecdc.europa.eu/en).

And yes, there will be meetings - if you let us know your email address (e.g. via the [contact form](https://covid19forecasthub.eu/contact/)) we'll add you to the mailing list.
