### ISSUE TITLE
Meta data content

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid19-forecast-hub-europe#5]
Can we have more detailed meta data with model categories?

SF: Good idea - can someone put a link to the metadata description for the US and Germany/Poland?

**Comment by seabbs** [comment]
Germany is sparse: https://github.com/KITmetricslab/covid19-forecast-hub-de/wiki/Preparing-your-submission#metadata

**Comment by kathsherratt** [comment]
US forecast [meta data readme](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#Meta-data)

**Comment by sbfnk** [comment]
Suggestions for other metadata fields?

**Comment by kathsherratt** [comment]
I've always thought a tabular meta data would be better to make it easy to compare across teams. Will compare the above and suggest something that will give us more detail with which to ensemble / compare models.

**Comment by seabbs** [comment]
I assume they have some code to read this into a csv.

**Comment by sbfnk** [comment]
of relevance: "We don't currently check the contents of metadata files, we just check they are there. You may want to go back to the US Hub to get the relevant codes for their current format (which is probably reasonable to adopt)."

**Comment by seabbs** [comment]
Edit: I think the US team have code.

**Comment by sbfnk** [comment]
US: https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/METADATA.md

**Comment by jbracher** [comment]
We don't really do much with the metadata currently (given time constraints we didn't give this as high priority as we maybe should have). So better follow the US example here. I think (but am not sure) that Zoltar also accesses metadata files, so you may want to check with Nick before making major changes here or moving to a tabular format.
