### ISSUE TITLE
Update list of required python packages for local checks?

### ISSUE THREAD

**Issue by jbracher** [epiforecasts/covid19-forecast-hub-europe#51]
I had to install pygithub as well which is missing from the list here: https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Check-submission Could somebody who knows these codes re-check all dependencies are listed?

**Comment by sbfnk** [comment]
pygithub has been added as of 9b9d24cb4a28be661b013afa6d18a690631c8db2 but it would still be good idea to double check this at some point.
