### ISSUE TITLE
New forecast format: integer values

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid19-forecast-hub-europe#537]
We are updating the hub forecast format to ensure that **all forecast values are integer counts**. 

This is new as we have not differentiated between integer and non-integer forecasts before. However we think forecasting whole counts makes sense given the forecast targets for cases and/or deaths. It also makes the hub more storage-efficient, which helps keep the project sustainable in the long term.

This will impact all forecast submitted to the hub.

### New submissions
- When formatting forecasts before submission, **please round values to an integer**
- You will also now see a warning message added to forecast submissions which have non-integer values 

### Existing forecasts
- We will be **updating all forecasts in the hub repo** to round all values to integers
- By default, we will use the `round()` function in `R` (where if the decimal is .5, the value is rounded to the nearest even integer)
- We aim to do this for all forecasts by **30 June**: please get in touch before then if you have any concerns

**Comment by kathsherratt** [comment]
Tagging hub contributors:
@jbracher @miraanto @BIOCOM-SC @RobertWalraven @gcgibson @seabbs @dwolffram @cyberklezmer @nikosbosse @aniruddhadiga @Barb-00 @Bisaloo @gr3gr3 @storaged @istirodiah @FrostXTJ @jlaznarte @pmontman @h-veronika @stefanheyder @hgurung-iem @sangeetabhatia03 @TaoSunVoyage @JADEUSC @dmorinya @kraus-stat @semohr @neele-itwm @holgerman @scc-usc

**Comment by neele-itwm** [comment]
Hi Kath,
Can you please confirm whether this applies also to all quantile-forecast values?
Thanks,
Neele

**Comment by kathsherratt** [comment]
Hi Neele - yes, this applies to all point and quantile forecasts. It's fine for multiple quantiles to have the same forecast values, as long as values are either equal or increase with increasing quantiles. 

For example, a forecast for quantiles 0.01 to 0.15 for one target/location could look like:

| forecast_date | target              | target_end_date | location | type     | quantile | value |
|---------------|---------------------|-----------------|----------|----------|----------|-------|
| 2021-06-21    | 1 wk ahead inc case | 2021-06-26      | AT       | quantile | 0.010     | 1     |
| 2021-06-21    | 1 wk ahead inc case | 2021-06-26      | AT       | quantile | 0.025    | 1     |
| 2021-06-21    | 1 wk ahead inc case | 2021-06-26      | AT       | quantile | 0.050     | 2     |
| 2021-06-21    | 1 wk ahead inc case | 2021-06-26      | AT       | quantile | 0.100      | 3     |
| 2021-06-21    | 1 wk ahead inc case | 2021-06-26      | AT       | quantile | 0.150      | 3     |

Hope that helps,

Kath

**Comment by sbfnk** [comment]
Closing this as the transition has been made successfully.
