### ISSUE TITLE
Use scales = "free_y" for facetted plot

### ISSUE THREAD

**Issue by Bisaloo** [epiforecasts/covid19-forecast-hub-europe#562]
see e.g.:

![image](https://user-images.githubusercontent.com/10783929/123408589-ae405c00-d59c-11eb-8fc6-48699d764b8b.png)

I think it is a bit unintuitive to read because models with different horizons don't have the same x-axis. It can easily be fixed by specifying `scales = "free_y"` instad of `scales = "free"`.

To avoid endless git conflicts, I'd like to wait until I'm done with #469 before changing this if you agree with this change.

**Comment by seabbs** [comment]
Is there a benefit to having free axis of any sort?

**Comment by Bisaloo** [comment]
In this case, not really. 

It simplifies a little bit the refactorisation to use the same code for this plot and the plot in the ensemble report. For the ensemble report, it's good because it's facetted by country and countries vary on different scales.

But I'm open to completely removing free axes in this plot if you feel it's better :shrug:

**Comment by sbfnk** [comment]
I think the risk is that for some countries you end up not doing anything if even just one blows the scale. Which is also the motivation behind this [mad hack](https://github.com/epiforecasts/scoringutils/pull/107/commits/8b8308d90891aa7b2d4e4a5eec1bd3fd447fd1b9) achieving per-country limits in the ensemble report. 

That said there’s definitely scope for experimenting with a few designs and see if there’s something that works better.

**Comment by seabbs** [comment]
Ah I hadn't considered crazed forecasts - definitely a good idea to keep the y axis free then.

**Comment by sbfnk** [comment]
(PS: agree with making x-axis not-free)

**Comment by Bisaloo** [comment]
You make a good point about having a forecast that makes all the others look flat when `scales = "fixed"` but at the same time, it is not always super easy to read when forecasts vary on quite different axes. Example of Ireland for 2021-07-12:

![image](https://user-images.githubusercontent.com/10783929/125598702-57e4e2f9-8c3c-41ca-b272-7eb8baff3506.png)

I don't have any better suggestion at the moment though :shrug:

**Comment by sbfnk** [comment]
Could experiment with either a log scale (though we do have zeroes, e.g. deaths in Iceland) or `coord_cartesian` limiting the max to some fixed multiple of the maximum data point (hiding extreme forecasts). People can always see the full forecasts in the visualisation app so I think cutting off wouldn't be too much of a problem here.
