### ISSUE TITLE
Display all forecast diagnostics in a single plot with facets

### ISSUE THREAD

**Issue by Bisaloo** [epiforecasts/covid19-forecast-hub-europe#563]
Currently, the various forecast diagnostics in `evaluation-by-country.Rmd` are displayed in different tabs. The tabs are very useful in many parts of the website but I think their potential overuse makes it difficult to navigate in the website and locate the various bits of informations.

![image](https://user-images.githubusercontent.com/10783929/123454916-9a165200-d5d0-11eb-814d-f4de35600ade.png)

In this case, I think all diagnostics (WIS, overprediction, underprediction, sharpness) could be displayed in a single plot facetted with `diagnostic ~ target_variable` instead of the current `~ target_variable`.

Additionally, it would be very cool if this plot could be converted to (gg)plotly so users can select only models they are interested in. It would be easier to read. But that's a slightly different issue.

**Comment by sbfnk** [comment]
Completely agree on both issues.

**Comment by Bisaloo** [comment]
Something like this (but with better labels, etc.)? 

![image](https://user-images.githubusercontent.com/10783929/124748443-aa082d00-df12-11eb-94ef-bf8662be3bf8.png)

Facetting forces all scores to be on the scale but since you mention in #638 that these 4 indices vary on the same scale as the observations, it's maybe not so big of an issue?

**Comment by sbfnk** [comment]
I think it's better but also I think (as you mentioned) the bigger issue is that these plots are pretty unreadable because of the overlap and similarity in colours. I'm not sure what the solution to that would be - maybe (gg)plotly, or a clone of the [US dashboard](https://delphi.cmu.edu/forecast-eval/)? Either way would be a fairly major change so probably worth thinking about what's feasible/sensible.

**Comment by Bisaloo** [comment]
This issue is no longer relevant since the reports have been completely overhauled. These plots do not exist in the current version.
