### ISSUE TITLE
Update columns in evaluation reports

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#594]
Following discussion with @jbracher: at the moment we have quite a lot of columns in the evaluation reports, and some of them are not very meaningful because they're not really comparable between models (e.g., wis, mae etc. unless two models have made forecasts for exactly the same set of dates). Also, we currently only list models that make forecasts for all quantiles, which is a bit restrictive as we could, e.g., compare models by MAE even if they make only point forecasts.

A suggestion is to change the table to have the following columns:
- `n`: all models. number of forecasts made.
- `n_loc`: all models. number of locations for which forecasts are made (relevant for "Overall" report only as for the country reports `n_loc==1` but I think there's no harm in keeping it in allowing us to maintain a single code base for all evaluation reports).
- `rel_wis`: only models that provide all quantiles (otherwise empty/NA). Same as `rel_skill` currently but renamed for clarity. 
- `rel_mae`: all models. Same as `rel_skill` currently but comparing by MAE instead of WIS. @nikosbosse does this functionality exist already in `scoringutils`?
- `50% cov`: only models that provide 0.25 and 0.75 quantile levels. As currently.
- `95% cov`: only models that provide 0.025 and 0.975 quantile levels. As currently.
- `bias`: all models. As currently.

We could then consider bringing back the [plots of relative contributions to WIS](https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/code/reports/evaluation/template-wis-components.Rmd) as this would be dropped from the tables. 

I think we should stick with only including models that have produced forecasts for the last 4 weeks to encourage ongoing participation and not e.g., keep models that were only submitted a few times a long time in the past.

**Comment by nikosbosse** [comment]
Yes, when computing the relative scores in eval_forecasts you can set a metric (wis is just the default)

**Comment by nikosbosse** [comment]
I think (but am not entirely sure) that eval_forecasts can also handle differing quantiles - so if one forecast has all quantiles and another one doesn't I think it would just work with what's there
