### ISSUE TITLE
Minimal/relaxed submission 

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid19-forecast-hub-europe#6]
NB: What is the criteria  for the "relaxed submission" where people only submit a median? point forecast? plus a certain quantile (which one?)

SF: I'd suggest at the very minimum we'd want the median, 50% and 90% prediction intervals.

**Comment by sbfnk** [comment]
We'll stick with `c(0.01, 0.025, seq(0.05, 0.95, by = 0.05), 0.975, 0.99)` or point forecast as they do in the other hubs.
