### ISSUE TITLE
Add metadata for EpiNow2_secondary and EpiExperts_Rt

### ISSUE THREAD

**Issue by jbracher** [epiforecasts/covid19-forecast-hub-europe#60]
@seabbs and @nikosbosse could you add metadata files for EpiNow2_secondary and EpiExperts_Rt and then move back the respective forecast files from data-temp to data-processed? You may also want to check the metadata files I added for your primary models [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/data-processed/epiforecasts-EpiExpert/metadata-epiforecasts-EpiExpert.txt) and [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/main/data-processed/epiforecasts-EpiNow2/metadata-epiforecasts-EpiNow2.txt).

**Comment by seabbs** [comment]
Closing as merging some models for the ECDC hub.
