### ISSUE TITLE
Round evaluation scores

### ISSUE THREAD

**Issue by Bisaloo** [epiforecasts/covid19-forecast-hub-europe#638]
Related: #614 

Currently, the scores stored in the `evaluation/` folder use up to 12 decimals. I'm not sure it makes sense in most cases. Would it make sense to round these scores as in #600 (not necessarily to the integer but at least reduce the number of digits)?

example: https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/3743ef7c838bbf0ed96b44f37add6249f54a0e9d/evaluation/evaluation-2021-04-05.csv

It would also help to reduce the size of the repo (and the diffs). At the moment, it's suboptimal but still manageable but it's starting to cause serious issues in the US hub: https://github.com/reichlab/covid19-forecast-hub/issues/3313

**Comment by sbfnk** [comment]
Very good idea. On a quick look through: 
- `interval_score`, `sharpness`, `underprediction`, `overprediction`, `aem` are all at the scale of the data and I think can safely be rounded to integers.
- `mae` is duplicated from `aem` and can be removed
- all other ones have absolute value <=1 and can be rounded to 2 digits after the decimal point.

**Comment by Bisaloo** [comment]
Should we consider proposing this change upstream to scoringutils?

**Comment by sbfnk** [comment]
Not sure it's easily enough generalised - e.g. my suggestion above is not easily encoded in a number of significant digits that could be an argument to `eval_forecasts`. My hunch is that this is best left for postprocessing by the user. @nikosbosse any thoughts?

**Comment by nikosbosse** [comment]
Agree with Seb that it might add some extra complexity to implement rounding in scoringutils. We could definitely do it, but I wouldn't treat it as a top priority. 

@sbfnk are you sure aem and mae are the same? I imagine that one might be computed based on the median forecast and one based on the point forecast which might differ. I don't know it for sure, but we should double-check

**Comment by sbfnk** [comment]
Ah maybe. In that case I think we should only look at the absolute error of the point forecast.
