### ISSUE TITLE
ensemble plots need to have greater `fig.height`

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#671]
The plot at https://covid19forecasthub.eu/reports/ensemble-report.html is squashed. It used to have `fig.height=14` (https://github.com/epiforecasts/covid19-forecast-hub-europe/commit/e7dde7f1bed33fb1be8433f8978dc3c8f488cf4d#diff-f65330c9ef062738afa7ab50548a7c4949f550eb6e5802aa1565d85e3f5b7441) but now 8 like the other forecast plots.

I guess ideally the height would be set dynamically based on the number of rows (number of models in the evaluation reports, number of countries in the ensemble report) but otherwise can we set this back to 14 somehow?

**Comment by Bisaloo** [comment]
Now redeployed with correct dimensions: https://covid19forecasthub.eu/reports/ensemble-report.html

**Comment by sbfnk** [comment]
Super, thanks!
