### ISSUE TITLE
Define submission period

### ISSUE THREAD

**Issue by kathsherratt** [epiforecasts/covid19-forecast-hub-europe#7]
NB: Do we allow submissions in between the actual submission dates? (I would suggest we don't and I would also suggest we force people to put the correct submission date in their submission files)

SF: So how long would the submission period be?

**Comment by sbfnk** [comment]
See also https://github.com/epiforecasts/covid19-forecast-hub-europe/issues/2

**Comment by kathsherratt** [comment]
@nikosbosse what has been your experience of handling submissions over several days? i have only submitted to the US on a monday and from that experience would guess a single day with a time window is easiest to handle as an admin.

**Comment by sbfnk** [comment]
In the absence of any change to the release schedule, submission period will be Thursday to Monday.
