### ISSUE TITLE
Facets with no forecasts in evaluation report

### ISSUE THREAD

**Issue by Bisaloo** [epiforecasts/covid19-forecast-hub-europe#759]
For some reason, models from Imperial appear in the plot but without showing any forecast:

![image](https://user-images.githubusercontent.com/10783929/128365886-5f8e4a5c-4155-46ff-b5bb-8d9457e4c6e2.png)

From https://covid19forecasthub.eu/reports/evaluation-report-Spain.html

There is probably a good reason for this but it's not obvious to me :thinking:.

**Comment by sbfnk** [comment]
I think it's because they only make one-week forecasts, i.e. no ribbon appears. A better way of visualising might be to make the ribbon start from the last data point instead of the first forecast week.

**Comment by sbfnk** [comment]
Closed as duplicate of #1020.
