### ISSUE TITLE
Duplication of location files

### ISSUE THREAD

**Issue by nikosbosse** [epiforecasts/covid19-forecast-hub-europe#77]
There is one here: https://github.com/epiforecasts/covid19-forecast-hub-europe/tree/main/data-locations
and one here: https://github.com/epiforecasts/covid19-forecast-hub-europe/tree/main/viz

**Comment by sbfnk** [comment]
We'll keep both in but they're now synchronised daily as of #158 - everything in `viz` is just for visualisation so there is some unavoidable duplication.
