### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/covid19-forecast-hub-europe#9]
The format described in https://github.com/reichlab/covid19-forecast-hub/tree/master/data-processed#Data-formatting is probably fit for purpose but we should replace the FIPS code with a [NUTS](https://ec.europa.eu/eurostat/web/nuts/background) code.

**Comment by sbfnk** [comment]
Should also review & understand differences with https://github.com/KITmetricslab/covid19-forecast-hub-de/wiki/Forecast-Data-Format

**Comment by sbfnk** [comment]
Also need to decide on file name structure. i can't see why one wouldn't use <date>-<team>-<model>.csv but to be discussed further.

**Comment by sbfnk** [comment]
update: having `<date>-<country>-<team>-<model>.csv` "would allow filtering by country without having to read in all files" which is worth considering.

**Comment by sbfnk** [comment]
Also mentioned in https://github.com/epiforecasts/covid19-forecast-hub-europe/issues/2

**Comment by kathsherratt** [comment]
Re the naming structure, agreed filtering would be nice but I'm not sure how that would work for forecasts with multiple countries (unless expecting separate csv files - quite a pain to PR in that case). Personally in favour of `<date>-<team>-<model>.csv`.

Will review data format. When agreed we should set up an example template.

**Comment by sbfnk** [comment]
We should also allow for scenarios (e.g. vaccination) - probably best to add a column to the submission which takes values of either "forecast" or the name of a scenario.

**Comment by sbfnk** [comment]
The data formats are near identical - Germany/Poland has an optional `location_name` field which we don't need. We'll add a `scenario` column, though, which should be `forecast` for forecasts and the name of a scenario if it is a scenario.
