### ISSUE TITLE
Update GitHub command line wiki section

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid19-forecast-hub-europe#97]
Currently the wiki command line section is partially command line based and partially GitHub interface based. It would be nice to update it to mention the GitHub CLI tools which allow for a fully command line based approach. 

An example of this implemented for the Epiforecast forecasts is here: https://github.com/epiforecasts/europe-covid-forecast/blob/master/submissions/submit.sh

The key line is `gh pr create` (with a `gh auth login` call required to initialise).

**Comment by sbfnk** [comment]
This is the same request as #15, right? Do you want to add a section to the wiki? Could be as simple as sayint that this is possible and link to your script.

**Comment by seabbs** [comment]
Done here: https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Submission-via-command-line

**Comment by sbfnk** [comment]
Great stuff - thanks!
